### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Jianjin123** [benedekrozemberczki/APPNP#1]
Hi, thanks for you sharing your nice work. 
I have a question when I run your code. Maybe I misunderstand the main point of this paper. It seems that when you train you model, you do not apply the graph information, which means your network is a normal fully connected network. After training, you apply PageRank to the output of the network when evaluate the model. Is my understanding correct?

**Comment by benedekrozemberczki** [comment]
Look at the code of the authors.

**Comment by Jianjin123** [comment]
Thanks. I thought this was the original code

**Comment by yhs95** [comment]
What is your pytorch version?

**Comment by benedekrozemberczki** [comment]
Did you read the readme?
